// WALLPAPER
export const LOAD_WALLPAPERS = 'LOAD_WALLPAPERS';
export const LOAD_WALLPAPERS_SUCCESS = 'LOAD_WALLPAPERS_SUCCESS';
export const LOAD_WALLPAPERS_ERROR = 'LOAD_WALLPAPERS_ERROR';
export const SET_TOTAL_WALLPAPER = 'SET_TOTAL_WALLPAPER';
export const SET_PAGE = 'SET_PAGE';

// CATEGORY
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_CATEGORIES_ERROR = 'LOAD_CATEGORIES_ERROR';
export const LOAD_CATEGORY_BY_NAME = 'LOAD_CATEGORY_BY_NAME';
export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';
export const LOAD_CATEGORY_BY_NAME_ERROR = 'LOAD_CATEGORY_BY_NAME_ERROR';

// GLOBAL
export const SET_SCREEN_SIZE = 'SET_SCREEN_SIZE';
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';
