export const LOAD_BRANDS = 'LOAD_BRANDS';
export const FILTER_BRANDS = 'FILTER_BRANDS';
export const LOAD_BRANDS_SUCCESS = 'LOAD_BRANDS_SUCCESS';
export const LOAD_BRANDS_ERROR = 'LOAD_BRANDS_ERROR';
