// DEVICE
export const LOAD_WALLPAPERS = 'LOAD_WALLPAPERS';
export const LOAD_WALLPAPERS_SUCCESS = 'LOAD_WALLPAPERS_SUCCESS';
export const LOAD_WALLPAPERS_ERROR = 'LOAD_WALLPAPERS_ERROR';
export const SET_PAGE = 'SET_PAGE';

// GLOBAL
export const SET_DEVICE_BRAND = 'SET_DEVICE_BRAND';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_SELECTED_DEVICE = 'SET_SELECTED_DEVICE';
export const LOAD_DEVICE_BY_NAME = 'LOAD_DEVICE_BY_NAME';
export const LOAD_DEVICE_BY_NAME_ERROR = 'LOAD_DEVICE_BY_NAME_ERROR';

